apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: sbenv
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: sbenv
  annotations:
    autoscaling.knative.dev/min-scale: "1"
spec:
  source:
    git:
      url: https://github.com/alexandreroman/sbenv
      ref:
        branch: testing
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
#  serviceClaims:
#  - name: db
#    ref:
#      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
#      kind: ClassClaim
#      name: sbenv-db
