name: sbenv

on:
  push:
    branches:
    - main
    - testing
    paths:
    - .github/workflows/**
    - src/**
    - pom.xml

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  call-deploy-image:
    uses: ./.github/workflows/_deploy.yaml
    with:
      native: true
